"""
Report Generator Agent - Creates structured incident reports

This agent generates comprehensive incident reports including:
- Incident summary and timeline
- Impact assessment
- Current status and next steps
- Communication updates
"""

import structlog
from typing import Dict, Any
import google.generativeai as genai
from datetime import datetime

logger = structlog.get_logger()


class ReportGeneratorAgent:
    """
    Specialized agent for generating incident reports.
    """

    def __init__(self, config: Dict[str, Any]):
        """
        Initialize the report generator agent.

        Args:
            config: Configuration dictionary
        """
        self.config = config
        self.model_name = config.get("agents", {}).get("report_generator", {}).get("model", "gemini-2.5-flash")
        self.temperature = config.get("agents", {}).get("report_generator", {}).get("temperature", 0.4)

        self.model = genai.GenerativeModel(self.model_name)

        logger.info("report_generator_initialized", model=self.model_name)

    async def generate_report(self, incident_data: Dict[str, Any]) -> str:
        """
        Generate a structured incident report.

        Args:
            incident_data: Incident information including severity, timeline, impact

        Returns:
            Formatted incident report as markdown string
        """
        logger.info("generating_report", incident_id=incident_data.get("incident_id"))

        try:
            # Build prompt for report generation
            prompt = self._build_report_prompt(incident_data)

            # Generate report with Gemini
            response = self.model.generate_content(prompt)

            # Create full report with metadata and AI-generated content
            report = self._format_report(incident_data, response.text)

            logger.info("report_generated", incident_id=incident_data.get("incident_id"))
            return report

        except Exception as e:
            logger.error("report_generation_failed", error=str(e), incident_id=incident_data.get("incident_id"))
            # Return basic template on failure
            return self._fallback_report(incident_data)

    def _build_report_prompt(self, incident_data: Dict[str, Any]) -> str:
        """Build prompt for incident report generation."""

        prompt = f"""You are an experienced SRE writing an incident status report.

INCIDENT DETAILS:
- Incident ID: {incident_data.get('incident_id', 'N/A')}
- Title: {incident_data.get('title', 'Unknown')}
- Severity: {incident_data.get('severity', 'Unknown')}
- Affected Services: {', '.join(incident_data.get('affected_services', []))}
- Error Messages: {', '.join(incident_data.get('error_messages', []))}
- Recommended Actions: {', '.join(incident_data.get('recommended_actions', []))}
- Status: {incident_data.get('status', 'Active')}

Generate a clear, professional incident report with these sections:

## Executive Summary
[2-3 sentences describing what happened, the impact, and current status]

## Timeline
[Reconstruct the timeline of events so far, including:
- When the alert was triggered
- Key actions taken
- Current state]

## Impact Assessment
[Describe:
- Which services/systems are affected
- Estimated customer impact
- Business impact]

## Current Status
[What's happening right now:
- Investigation progress
- Mitigation efforts
- Team members involved]

## Next Steps
[Immediate action items:
1. [Priority actions to resolve or mitigate]
2. [Monitoring and verification steps]
3. [Communication plan]]

Keep it factual, clear, and actionable. Use professional SRE language."""

        return prompt

    def _format_report(self, incident_data: Dict[str, Any], ai_content: str) -> str:
        """Format the complete report with metadata."""

        return f"""# Incident Report: {incident_data.get('title', 'Unknown')}

**Incident ID:** {incident_data.get('incident_id', 'N/A')}
**Severity:** {incident_data.get('severity', 'Unknown')}
**Status:** {incident_data.get('status', 'Active')}
**Created:** {datetime.now().isoformat()}
**Affected Services:** {', '.join(incident_data.get('affected_services', ['Unknown']))}

---

{ai_content}

---

*Report generated by Incident Response Bot*
"""

    def _fallback_report(self, incident_data: Dict[str, Any]) -> str:
        """Generate basic report if Gemini fails."""

        return f"""# Incident Report: {incident_data.get('title', 'Unknown')}

**Incident ID:** {incident_data.get('incident_id', 'N/A')}
**Severity:** {incident_data.get('severity', 'Unknown')}
**Status:** {incident_data.get('status', 'Active')}
**Created:** {datetime.now().isoformat()}

## Summary
{incident_data.get('title', 'Incident detected')}

Severity: {incident_data.get('severity', 'Unknown')}
Affected Services: {', '.join(incident_data.get('affected_services', []))}

## Symptoms
{', '.join(incident_data.get('error_messages', ['No details available']))}

## Recommended Actions
{chr(10).join(f'- {action}' for action in incident_data.get('recommended_actions', ['Investigate', 'Monitor']))}

## Status
Incident is currently {incident_data.get('status', 'active')}. Investigation in progress.

---

*Basic report generated - Gemini unavailable*
"""
